/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.elaboraciondeactividadesdelaorganizacion.VistaControl.secretario;

import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.clasedeaccionesdeproductos;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasedecargadeinventario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtoproducto;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.model.producto;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.BaseDeTransformacion;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.DeStringaDouble;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.DeStringaInt;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.crearproducto;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.verproducto;
import java.util.List;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author x
 */
public class AccionesdelInventario extends javax.swing.JFrame implements interfasedecargadeinventario{

    /**
     * Creates new form AccionesdelInventario
     */
    public AccionesdelInventario() {
        initComponents();
        TablaMouseClicked();
        Cargarproductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        InCantidad = new javax.swing.JTextField();
        InNombre = new javax.swing.JTextField();
        InDescripcion = new javax.swing.JTextField();
        InEstado = new javax.swing.JTextField();
        InIDVenta = new javax.swing.JTextField();
        InPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensaje = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane2.setBackground(new java.awt.Color(255, 0, 51));
        jScrollPane2.setForeground(new java.awt.Color(102, 51, 255));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaProducto);

        jToggleButton1.setText("Crear");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Actualizado");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Eliminaar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Limpiar");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Administracion con el inventario");

        jLabel2.setText("IDventa");

        jLabel3.setText("Nombre");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Precio");

        jLabel6.setText("Descripcion");

        jLabel8.setText("Estado");

        InCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InCantidadActionPerformed(evt);
            }
        });

        InDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InDescripcionActionPerformed(evt);
            }
        });

        Mensaje.setColumns(20);
        Mensaje.setRows(5);
        jScrollPane1.setViewportView(Mensaje);

        jLabel7.setText("Mensaje++++++++++++++++//////+++++");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(InNombre)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(InIDVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel5)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(InCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(InPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 79, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(InEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(InDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel7)))
                .addGap(604, 604, 604))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jToggleButton2)
                        .addGap(80, 80, 80)
                        .addComponent(jToggleButton3)
                        .addGap(37, 37, 37)
                        .addComponent(jToggleButton4)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(InDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InIDVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(InNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(InEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InCantidadActionPerformed

    private void InDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InDescripcionActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        actualizarproducto();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
       eliminarproducto();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // limpiar
        InIDVenta.setText("");
        InNombre.setText("");
        InCantidad.setText("");
        InPrecio.setText("");
        InDescripcion.setText("");
        InEstado.setText("");
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        crearproducto();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MenuSecretarioGUI men = new MenuSecretarioGUI();
       men.setVisible(true);
       AccionesdelInventario.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InCantidad;
    private javax.swing.JTextField InDescripcion;
    private javax.swing.JTextField InEstado;
    private javax.swing.JTextField InIDVenta;
    private javax.swing.JTextField InNombre;
    private javax.swing.JTextField InPrecio;
    private javax.swing.JTextArea Mensaje;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
private clasedeaccionesdeproductos productactioncontroll = new clasedeaccionesdeproductos();
    @Override
    public void Cargarproductos() {
        verproducto creadorlista = productactioncontroll.getVerproductoobject();
    String[] columna = {"ID+Producto","Nombre","cantidad","precio","descripcion","Estado"};
        DefaultTableModel modelo = (DefaultTableModel) TablaProducto.getModel();
        modelo.setColumnIdentifiers(columna);
        modelo.setRowCount(0);
    List<dtoproducto> todoslosproductos = creadorlista.Entrega();
    Object[] objeto = new Object[6];
    for(dtoproducto dtop : todoslosproductos){
    objeto[0] = dtop.getC().getIdProducto();
    objeto[1] = dtop.getC().getNombre();
    objeto[2] = dtop.getC().getCantidad();
    objeto[3] = dtop.getC().getPrecio();
    objeto[4] = dtop.getC().getDescripcion();
    objeto[5] = dtop.getC().getEstado();
    modelo.addRow(objeto);
    }
    String textomensaje = Mensaje.getText();
    Mensaje.setText(textomensaje+"\n Cargo la tabla con el producto");
    
    }

    @Override
    public void crearproducto() {
   crearproducto crearnuevoproducto = productactioncontroll.getCrearproductoobject();
        BaseDeTransformacion<String, Double> basedetransformacion = new DeStringaDouble();
       DeStringaInt basedetransformacion2 = new DeStringaInt();
        
    producto p = new producto();
    p.setIdProducto(InIDVenta.getText());
    p.setNombre(InNombre.getText());;
    p.setCantidad(basedetransformacion2.Tranformacion(InCantidad.getText()));
    p.setPrecio(basedetransformacion.Tranformacion(InPrecio.getText()));
    p.setDescripcion(InDescripcion.getText());
    p.setEstado(basedetransformacion2.Tranformacion(InEstado.getText()));
    dtoproducto dtop = new dtoproducto(p);
    String texomensaje = Mensaje.getText();
    String entrega = productactioncontroll.getCrearproductoobject().regusitrar(dtop);
    Mensaje.setText(texomensaje+ entrega);
    Cargarproductos();
    }

    @Override
    public void actualizarproducto() {
      BaseDeTransformacion<String, Double> basedetransformacion = new DeStringaDouble();
       DeStringaInt basedetransformacion2 = new DeStringaInt();
        
    producto p = new producto();
    p.setIdProducto(InIDVenta.getText());
    p.setNombre(InNombre.getText());;
    p.setCantidad(basedetransformacion2.Tranformacion(InCantidad.getText()));
    p.setPrecio(basedetransformacion.Tranformacion(InPrecio.getText()));
    p.setDescripcion(InDescripcion.getText());
    p.setEstado(basedetransformacion2.Tranformacion(InEstado.getText()));
    dtoproducto dtop = new dtoproducto(p);
    String texomensaje = Mensaje.getText();
    String entrega = productactioncontroll.getActualizarproductoobject().actualizardato(dtop);
    Mensaje.setText(texomensaje+ entrega);
    Cargarproductos();
        
    
    
    
    
    }

    @Override
    public void eliminarproducto() {
    BaseDeTransformacion<String, Double> basedetransformacion = new DeStringaDouble();
       DeStringaInt basedetransformacion2 = new DeStringaInt();
        
    producto p = new producto();
    p.setIdProducto(InIDVenta.getText());
    p.setNombre(InNombre.getText());;
    p.setCantidad(basedetransformacion2.Tranformacion(InCantidad.getText()));
    p.setPrecio(basedetransformacion.Tranformacion(InPrecio.getText()));
    p.setDescripcion(InDescripcion.getText());
    p.setEstado(basedetransformacion2.Tranformacion(InEstado.getText()));
    dtoproducto dtop = new dtoproducto(p);
    String texomensaje = Mensaje.getText();
    String entrega = productactioncontroll.getEliminarproductoobject().eliminardato(dtop);
    Mensaje.setText(texomensaje+ entrega);
    Cargarproductos();
        
    
    
    
    
    
    }


private void TablaMouseClicked() {

     TablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {

            int fila = TablaProducto.getSelectedRow();

            if (fila >= 0) {
                 InIDVenta.setText(TablaProducto.getValueAt(fila, 0).toString());
        InNombre.setText(TablaProducto.getValueAt(fila, 1).toString());
        InCantidad.setText(TablaProducto.getValueAt(fila, 2).toString());
        InPrecio.setText(TablaProducto.getValueAt(fila, 3).toString());
        InDescripcion.setText(TablaProducto.getValueAt(fila, 4).toString());
        InEstado.setText(TablaProducto.getValueAt(fila, 5).toString()); 


            }
        }
    });
}


}
