/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.elaboraciondeactividadesdelaorganizacion.VistaControl.secretario;

import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfacedeeliminaciondeventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasecargadecomponentespredefinidosactualizarventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasecargadeventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasedeCargadeventa;
import static com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasedeCargadeventa.verventaobject;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasedeeliminarfactura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfaserealizarventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtocliente;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtofactura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtoproducto;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtosecretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtoventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.model.factura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.model.venta;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.ComplementosdeCompletado.Complementodeinterfaceivairpf;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.BaseDeTransformacion;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.DeStringaDouble;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.DeStringaInt;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.actualizarproducto;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.verfactura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.verventa;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author x
 */
public class AccionDeVenta1 extends javax.swing.JFrame implements interfaserealizarventa, interfasedeCargadeventa, interfasecargadeventa, Complementodeinterfaceivairpf, interfasecargadecomponentespredefinidosactualizarventa, interfacedeeliminaciondeventa, interfasedeeliminarfactura {

    /**
     * Creates new form AccionDeVenta
     */
    public AccionDeVenta1() {
        initComponents();
        tablaVentaMouseClicked();
        verventas();
        verproducto();
        versecretario();
        verfactura();
   

    }
    
    
    public void granactualizacion(){
   
        verventas();
       
       
    
    }
    
private LocalDate fecha = LocalDate.now();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Producto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InIDCliente = new javax.swing.JTextField();
        InIDProducto = new javax.swing.JTextField();
        InCantidad = new javax.swing.JTextField();
        InEstado = new javax.swing.JTextField();
        InIDSecretario = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaVenta = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaSecretario = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Mensaje = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        InIDVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 153, 0));

        Producto.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("IDCliente");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("IDProducto");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("IDSecretario");

        InEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InEstadoActionPerformed(evt);
            }
        });

        TablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaVenta);

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TablaCliente);

        TablaSecretario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TablaSecretario);

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(TablaProducto);

        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(TablaFactura);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Mensaje++++>");

        Mensaje.setColumns(20);
        Mensaje.setForeground(new java.awt.Color(0, 0, 0));
        Mensaje.setRows(5);
        jScrollPane8.setViewportView(Mensaje);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("IDVenta");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Venta");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cliente");

        jLabel10.setText("jLabel10");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Producto");

        jLabel12.setText("jLabel12");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Secretario");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Factura");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Acciones de venta");

        javax.swing.GroupLayout ProductoLayout = new javax.swing.GroupLayout(Producto);
        Producto.setLayout(ProductoLayout);
        ProductoLayout.setHorizontalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel14)
                        .addContainerGap())
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel1)))
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(InIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(InIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(InIDVenta)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(InCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(ProductoLayout.createSequentialGroup()
                                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(InIDSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(InEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(101, 101, 101)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton4)
                                            .addComponent(jButton2))))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane7))
                .addGap(40, 40, 40))
            .addGroup(ProductoLayout.createSequentialGroup()
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(ProductoLayout.createSequentialGroup()
                            .addGap(461, 461, 461)
                            .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addGroup(ProductoLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12))))
                        .addGroup(ProductoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(529, 529, 529)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProductoLayout.setVerticalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(InIDVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(InIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(InCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addGap(14, 14, 14)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(InEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(InIDSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel11))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(41, 41, 41)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(Producto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InEstadoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MenuSecretarioGUI ms = new MenuSecretarioGUI();
        ms.setVisible(true);
        AccionDeVenta1.this.dispose();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    InCantidad.setText("");
        InEstado.setText("");
        InIDCliente.setText("");
        InIDProducto.setText("");
        InIDSecretario.setText("");
        InIDVenta.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearventas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualizarventa();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       eliminarventa();
    }//GEN-LAST:event_jButton3ActionPerformed
    public void tablaVentaMouseClicked() {
        TablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = TablaVenta.getSelectedRow();
                if (fila >= 0) {
                    InIDVenta.setText(TablaVenta.getValueAt(fila, 0).toString());
                    InIDCliente.setText(TablaVenta.getValueAt(fila, 1).toString());
                    InIDProducto.setText(TablaVenta.getValueAt(fila, 2).toString());
                    InEstado.setText(TablaVenta.getValueAt(fila, 5).toString());
//                    InCantidad.setText(TablaFactura.getValueAt(fila, 2).toString());
//                    InIDSecretario.setText(TablaFactura.getValueAt(fila, 8).toString());
                }
            }
        });

        TablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = TablaFactura.getSelectedRow();
                if (fila >= 0 && TablaFactura.getRowCount() > 0) {
                    InCantidad.setText(TablaFactura.getValueAt(fila, 2).toString());
                    InIDSecretario.setText(TablaFactura.getValueAt(fila, 8).toString());
                }
            }
        });
   
      TablaVenta.addMouseListener(
                new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = TablaVenta.getSelectedRow();
                String idCliente = "";
                if (fila >= 0) {
                    idCliente = (String) TablaVenta.getValueAt(fila, 1);
                }
                List<dtocliente> lista1 = verventaobject.EntregarComplementocliente();
                List<dtocliente> lista2 = verventaobject.buscarcliente(idCliente, lista1);
                cargarcliente1(lista2);

            }

        }
        );
        String textomensaje = Mensaje.getText();
        Mensaje.setText(
                textomensaje + "Tabla de clientes se actualizada.");
    
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InCantidad;
    private javax.swing.JTextField InEstado;
    private javax.swing.JTextField InIDCliente;
    private javax.swing.JTextField InIDProducto;
    private javax.swing.JTextField InIDSecretario;
    private javax.swing.JTextField InIDVenta;
    private javax.swing.JTextArea Mensaje;
    private javax.swing.JPanel Producto;
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTable TablaFactura;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JTable TablaSecretario;
    private javax.swing.JTable TablaVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void verventas() {
        DefaultTableModel modelo = (DefaultTableModel) TablaVenta.getModel();
        String[] columnas = {"ID Venta", "IDCliente ", "IDProducto", "Valor a pagar", "FechaVenta", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);
        verventa vv = new verventa();
        List<dtoventa> lista = vv.Entrega();
        for (dtoventa dtov : lista) {
            modelo.addRow(new Object[]{
                dtov.getC().getIdVenta(),
                dtov.getC().getIdCliente(),
                dtov.getC().getIdProducto(),
                dtov.getC().getValorAPagar(),
                dtov.getC().getFechaVenta(),
                dtov.getC().getEstado()
            });
        }
        Mensaje.setText("Tabla de ventas actualizada.");

    }
    private dtoventa ventadto = new dtoventa();
private dtofactura facturadto = new dtofactura();

private int catidad;
    @Override
    public void crearventas() {
         DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
   venta v = new venta();
   DeStringaInt di = new DeStringaInt();
   DeStringaDouble sd = new DeStringaDouble();
   v.setIdVenta( di.Tranformacion(InIDVenta.getText()));
    v.setIdCliente(InIDCliente.getText());
    v.setIdProducto(InIDProducto.getText());
    v.setValorAPagar(sd.Tranformacion(InCantidad.getText())*preciofijo);
    v.setFechaVenta(this.fecha.format(formateador));
v.setEstado(1);
String textomensaje = Mensaje.getText();
Mensaje.setText(textomensaje+"\n Se cargo la venta");
double total = sd.Tranformacion(InCantidad.getText())*preciofijo;
ventadto.setC(v);
crearventaobjeto.regusitrar(ventadto);
this.catidad = di.Tranformacion(InCantidad.getText());
factura f = new factura();
f.setIdFactura(1);
f.setIdVenta(di.Tranformacion(InIDVenta.getText()));
f.setCantidad(di.Tranformacion(InCantidad.getText()));
f.setSubTotal(total*IVA);
f.setFecha(this.fecha.format(formateador));
f.setCorreo("Null");
f.setIva(IVA);
f.setIrpf(IRPF);
f.setIdSecretario(InIDSecretario.getText());
facturadto.setC(f);
crearfacturaobjeto.regusitrar(facturadto);
 textomensaje = Mensaje.getText();
Mensaje.setText(textomensaje+"\n Se cargo la factura /(Complemento de venta)/");
        actualizarcantidadproducto(catidad, v.getIdProducto());
    granactualizacion();
    
    }

    @Override
    public void actualizarventa() {
         DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
   venta v = new venta();
   DeStringaInt di = new DeStringaInt();
   DeStringaDouble sd = new DeStringaDouble();
   v.setIdVenta( di.Tranformacion(InIDVenta.getText()));
    v.setIdCliente(InIDCliente.getText());
    v.setIdProducto(InIDProducto.getText());
    v.setValorAPagar(sd.Tranformacion(InCantidad.getText())*preciofijo);
    v.setFechaVenta(this.fecha.format(formateador));
v.setEstado(1);
String textomensaje = Mensaje.getText();
Mensaje.setText(textomensaje+"\n Se actualizo la venta");
double total = sd.Tranformacion(InCantidad.getText())*preciofijo;
ventadto.setC(v);
actualizarventaobject.actualizardato(ventadto);
factura f = new factura();
f.setIdFactura(1);
f.setIdVenta(di.Tranformacion(InIDVenta.getText()));
f.setCantidad(di.Tranformacion(InCantidad.getText()));
f.setSubTotal(total*IVA);
f.setFecha(this.fecha.format(formateador));
f.setCorreo("Null");
f.setIva(IVA);
f.setIrpf(IRPF);
f.setIdSecretario(InIDSecretario.getText());
facturadto.setC(f);
actualizarfacturaobject.actualizardato(facturadto);
 textomensaje = Mensaje.getText();
Mensaje.setText(textomensaje+"\n Se actualizo la factura /(Complemento de venta)/");
       granactualizacion();
    
    
    }

    @Override
    public void eliminarventa() {
         DeStringaInt di = new DeStringaInt();
   DeStringaDouble sd = new DeStringaDouble();
   
factura f = new factura();
f.setIdFactura(idfacturageneral);
f.setIdVenta(0);
f.setCantidad(0);
f.setSubTotal(0);
f.setFecha("");
f.setCorreo("Null");
f.setIva(IVA);
f.setIrpf(IRPF);
f.setIdSecretario("");
facturadto.setC(f);
eliminarfacturaobject.eliminardato(facturadto);

String  textomensaje = Mensaje.getText();
Mensaje.setText(textomensaje+"\n Se elimino la factura /(Complemento de venta)/");  



DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
   venta v = new venta();
  
   v.setIdVenta( di.Tranformacion(InIDVenta.getText()));
    v.setIdCliente("");
    v.setIdProducto("");
    v.setValorAPagar(0);
    v.setFechaVenta("");
v.setEstado(1);
 textomensaje = Mensaje.getText();
Mensaje.setText(textomensaje+"\n Se cargo la venta");

ventadto.setC(v);
eliminarventaobject.eliminardato(ventadto);
       granactualizacion();
    
    
    }
private int idfacturageneral;
    public void cargartablafactura(List<dtofactura> lista2) {
        DefaultTableModel modelo = (DefaultTableModel) TablaFactura.getModel();
        String[] columnas = {"idFactura", "idVenta", "cantidad", "sub Total", "fecha", "coreo", "IVA", "IRPF", "idSecretario"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);

        verfactura vf = new verfactura();
        List<dtofactura> lista = lista2;

        for (dtofactura dtof : lista) {
            this.idfacturageneral=dtof.getC().getIdFactura();
            modelo.addRow(new Object[]{
                dtof.getC().getIdFactura(),
                dtof.getC().getIdVenta(),
                dtof.getC().getCantidad(),
                dtof.getC().getSubTotal(),
                dtof.getC().getFecha(),
                dtof.getC().getCorreo(),
                dtof.getC().getIva(),
                dtof.getC().getIrpf(),
                dtof.getC().getIdSecretario()
            });
        }
        Mensaje.setText("Tabla de facturas actualizada.");
   granactualizacion();
    }

    public void verproducto() {
        TablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                BaseDeTransformacion<String, Integer> cmd = new DeStringaInt();
                int fila = TablaVenta.getSelectedRow();
                String idventa = "";
                if (fila >= 0) {
                    String idventas = TablaVenta.getValueAt(fila, 2).toString();
                    idventa = idventas;

                }
                List<dtoproducto> listafactura1 = verventaobject.EntregarComplementoproducto();
                List<dtoproducto> listafactura2 = verventaobject.buscarproducto(idventa, listafactura1);
                CargarTablaProducto(listafactura2);
            }
        });
  
    }

    public void versecretario() {
        TablaFactura.addMouseListener(
                new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = TablaFactura.getSelectedRow();
                String idsecretario = "";
                if (fila >= 0) {
                    idsecretario = (String) TablaFactura.getValueAt(fila, 8);
                }
                List<dtosecretario> listasecretario = verventaobject.EntregarComplementoSecretario();
                List<dtosecretario> listasecretario2 = verventaobject.buscarsecretario(idsecretario, listasecretario);
                cargarsecretario1(listasecretario);
            }

        }
        );

    }

    public void CargarTablaProducto(List<dtoproducto> lista2) {
        DefaultTableModel modelo = (DefaultTableModel) TablaProducto.getModel();
        String[] columnas = {"idProducto", "Nombre", "Cantidad", "Precio", "Descripcion", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);

        verfactura vf = new verfactura();
        List<dtoproducto> lista = lista2;

        for (dtoproducto dtop : lista) {
            this.preciofijo = dtop.getC().getPrecio();
            modelo.addRow(new Object[]{
                dtop.getC().getIdProducto(),
                dtop.getC().getNombre(),
                dtop.getC().getCantidad(),
                dtop.getC().getPrecio(),
                dtop.getC().getDescripcion(),
                dtop.getC().getEstado()
            }
            );
        }

        Mensaje.setText(
                "Tabla de productos actualizada.");
    }
private double preciofijo;
    public void verfactura() {
        TablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                BaseDeTransformacion<String, Integer> cmd = new DeStringaInt();
                int fila = TablaVenta.getSelectedRow();
                int idventa = 0;
                if (fila >= 0) {
                    String idventas = TablaVenta.getValueAt(fila, 0).toString();
                    idventa = (int) cmd.Tranformacion(idventas);

                }
                List<dtofactura> listafactura1 = verventaobject.EntregarComplementofactura();
                List<dtofactura> listafactura2 = verventaobject.buscarfactura(idventa, listafactura1);
                cargartablafactura(listafactura2);
            }
        });

    }

    @Override
    public void cargarcliente1(List<dtocliente> lista) {
        DefaultTableModel modelo = (DefaultTableModel) TablaCliente.getModel();
        String[] columnas = {"ID+Cliente", "Nombre", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);
        for (dtocliente dtoc : lista) {

            modelo.addRow(new Object[]{
                dtoc.getC().getIdCliente(),
                dtoc.getC().getNombre(),
                dtoc.getC().getEstado()
            });

        }

    }

    @Override
    public void cargarsecretario1(List<dtosecretario> lista) {
        DefaultTableModel modelo = (DefaultTableModel) TablaSecretario.getModel();
        String[] columnas = {"ID+Secretario", "Nombre", "Apellido", "Cedula", "Telefono", "Direccion", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);
        for (dtosecretario dtos : lista) {
            modelo.addRow(new Object[]{
                dtos.getC().getIdSecretario(),
                dtos.getC().getNombre(),
                dtos.getC().getApellido(),
                dtos.getC().getCedula(),
                dtos.getC().getTelefono(),
                dtos.getC().getDireccion(),
                dtos.getC().getEstado()
            });

        }
        String textomensaje = Mensaje.getText();
        Mensaje.setText(textomensaje + " secretario creado");
    }

    @Override
    public void cargarfactura1(List<dtofactura> lista) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void cargarventa1(List<dtoventa> lista) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void cargarproducto1(List<dtoproducto> lista) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void vercliente() {
          
        TablaVenta.addMouseListener(
                new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = TablaVenta.getSelectedRow();
                String idCliente = "";
                if (fila >= 0) {
                    idCliente = (String) TablaVenta.getValueAt(fila, 1);
                }
                List<dtocliente> lista1 = verventaobject.EntregarComplementocliente();
                List<dtocliente> lista2 = verventaobject.buscarcliente(idCliente, lista1);
                cargarcliente1(lista2);

            }

        }
        );
        String textomensaje = Mensaje.getText();
        Mensaje.setText(
                textomensaje + "Tabla de clientes se actualizada.");
    }

    public void actualizarcantidadproducto(int cantidadrestada, String ID){
    List<dtoproducto> lista1 = verventaobject.EntregarComplementoproducto();
    List<dtoproducto> lista2 = verventaobject.buscarproducto(ID, lista1);
    dtoproducto productoaactualizar = new dtoproducto();
    for(dtoproducto dtop : lista2){
        int CantidadBase = dtop.getC().getCantidad();
    dtop.getC().setCantidad(CantidadBase - cantidadrestada);
        productoaactualizar = dtop;
        
    }
        actualizarproducto actp = new actualizarproducto();
    actp.actualizardato(productoaactualizar);
        
    }    
}
