/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.elaboraciondeactividadesdelaorganizacion.VistaControl.secretario;

import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfacedeeliminaciondeventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasecargadecomponentespredefinidosactualizarventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasecargadeventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasedeCargadeventa;
import static com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasedeCargadeventa.verventaobject;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfasedeeliminarfactura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfaserealizarventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtocliente;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtofactura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtoproducto;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtosecretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtoventa;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.model.factura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.model.venta;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.ClaseGenerarTxt;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.ComplementosdeCompletado.Complementodeinterfaceivairpf;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.BaseDeTransformacion;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.DeStringaDouble;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.DeStringaInt;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.actualizarproducto;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.verfactura;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.verventa;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author x
 */
public class ActionFactura extends javax.swing.JFrame implements interfaserealizarventa, interfasedeCargadeventa, interfasecargadeventa, Complementodeinterfaceivairpf, interfasecargadecomponentespredefinidosactualizarventa, interfacedeeliminaciondeventa, interfasedeeliminarfactura {

    /**
     * Creates new form AccionDeVenta
     */
    public ActionFactura() {
        initComponents();
       tablaVentaMouseClicked(); // ← este solo hace todo
    verventas(); 
   

    }
    
    
    public void granactualizacion(){
   
        verventas();
       
       
    
    }
    
private LocalDate fecha = LocalDate.now();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Producto = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaVenta = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaSecretario = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Mensaje = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        InIDFactura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        InFecha = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        InEstadoFactura = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        InIDCliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        InNombreCliente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        InIDSecretario = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        InNombreSecretario = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        InApellidoSecretario = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        InCedulaSecretario = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        InIDVenta = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        InCantidadVenta = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        InSubTotalVenta = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        InIGVVenta = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        InTotalVenta = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        InIDProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InPrecioUnitarioProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InEstadoProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 153, 0));

        Producto.setBackground(new java.awt.Color(0, 204, 255));

        TablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaVenta);

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TablaCliente);

        TablaSecretario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TablaSecretario);

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(TablaProducto);

        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(TablaFactura);

        jButton1.setText("Crear factura .txt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Mensaje++++>");

        Mensaje.setColumns(20);
        Mensaje.setRows(5);
        jScrollPane8.setViewportView(Mensaje);

        jLabel7.setText("ID+Cliente");

        jLabel8.setText("Venta");

        jLabel9.setText("Cliente");

        jLabel11.setText("Producto");

        jLabel13.setText("Secretario");

        jLabel14.setText("Factura");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Factura de venta");

        jLabel10.setText("ID+Factura");

        jLabel12.setText("Fecha");

        jLabel16.setText("Estado");

        InEstadoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InEstadoFacturaActionPerformed(evt);
            }
        });

        jLabel17.setText("Datos de la factura");

        jLabel18.setText("Datos de cliente");

        jLabel19.setText("Nombre");

        jLabel22.setText("Datos del secretario");

        jLabel23.setText("ID+Secretario");

        jLabel24.setText("Nombre");

        jLabel25.setText("Apellido");

        jLabel26.setText("Cedula");

        InCedulaSecretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InCedulaSecretarioActionPerformed(evt);
            }
        });

        jLabel27.setText("Detalle de la venta");

        jLabel28.setText("ID+Venta");

        InIDVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InIDVentaActionPerformed(evt);
            }
        });

        jLabel29.setText("Cantidad");

        jLabel30.setText("SubTotal S/.");

        jLabel31.setText("IGV ");

        jLabel32.setText("Total S/.");

        jLabel33.setText("Detalle de producto");

        jLabel1.setText("ID+Producto");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio Unitario S/.");

        jLabel4.setText("Estado");

        javax.swing.GroupLayout ProductoLayout = new javax.swing.GroupLayout(Producto);
        Producto.setLayout(ProductoLayout);
        ProductoLayout.setHorizontalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276)
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)))
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(InIDVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InSubTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel31)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel33)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(InNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(InIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(InPrecioUnitarioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(InEstadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(184, 184, 184)
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 788, Short.MAX_VALUE))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(24, 24, 24)
                                        .addComponent(InNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel22)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(InIGVVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(InIDSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InNombreSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(InApellidoSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(InCedulaSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(168, 168, 168)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1341, Short.MAX_VALUE))
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jButton1))
                                        .addGap(69, 69, 69)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton4))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(jLabel15)
                                .addGap(185, 185, 185)
                                .addComponent(jLabel8))
                            .addGroup(ProductoLayout.createSequentialGroup()
                                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductoLayout.createSequentialGroup()
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(InIDFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(InFecha)
                                            .addComponent(InEstadoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                                    .addComponent(jLabel18))
                                .addGap(222, 222, 222)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ProductoLayout.setVerticalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addGap(2, 2, 2)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(InIDFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(InFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(InEstadoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)))
                .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProductoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(InIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(InNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(InIDSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(InNombreSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jLabel25)
                            .addComponent(InApellidoSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel26)
                            .addComponent(InCedulaSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(InIDVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(InCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(InSubTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(InIGVVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(InTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(InIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(InNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(InPrecioUnitarioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(InEstadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(Producto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1320, 1320, 1320))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InIDVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InIDVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InIDVentaActionPerformed

    private void InCedulaSecretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InCedulaSecretarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InCedulaSecretarioActionPerformed

    private void InEstadoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InEstadoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InEstadoFacturaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MenuSecretarioGUI ms = new MenuSecretarioGUI();
        ms.setVisible(true);
        ActionFactura.this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
limpiarCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        verventas();
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
creararchivotxt();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
   public void tablaVentaMouseClicked() {

    // Clic en TablaVenta → rellena campos de Venta, Cliente, Producto y Factura
    TablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = TablaVenta.getSelectedRow();
            if (fila >= 0) {

                // --- Detalle de la Venta ---
                InIDVenta.setText(TablaVenta.getValueAt(fila, 0).toString());
                InIDCliente.setText(TablaVenta.getValueAt(fila, 1).toString());
                InIDProducto.setText(TablaVenta.getValueAt(fila, 2).toString());
                InSubTotalVenta.setText(TablaVenta.getValueAt(fila, 3).toString());
                InFecha.setText(TablaVenta.getValueAt(fila, 4).toString());
                InEstadoFactura.setText(TablaVenta.getValueAt(fila, 5).toString());

                // --- Tabla Cliente → rellena Nombre, DNI/RUC, Teléfono ---
                String idCliente = TablaVenta.getValueAt(fila, 1).toString();
                List<dtocliente> listaC = verventaobject.EntregarComplementocliente();
                List<dtocliente> listaC2 = verventaobject.buscarcliente(idCliente, listaC);
                cargarcliente1(listaC2);
                for (dtocliente dtoc : listaC2) {
                    InNombreCliente.setText(dtoc.getC().getNombre());
                
                    
                }

                // --- Tabla Producto → rellena Nombre, Precio, Estado ---
                String idProducto = TablaVenta.getValueAt(fila, 2).toString();
                List<dtoproducto> listaP = verventaobject.EntregarComplementoproducto();
                List<dtoproducto> listaP2 = verventaobject.buscarproducto(idProducto, listaP);
                CargarTablaProducto(listaP2);
                for (dtoproducto dtop : listaP2) {
                    InIDProducto.setText(dtop.getC().getIdProducto());
                    InNombreProducto.setText(dtop.getC().getNombre());
                    InPrecioUnitarioProducto.setText(String.valueOf(dtop.getC().getPrecio()));
                    InEstadoProducto.setText(String.valueOf(dtop.getC().getEstado()));
                }

                // --- Tabla Factura ---
                BaseDeTransformacion<String, Integer> cmd = new DeStringaInt();
                int idVenta = (int) cmd.Tranformacion(TablaVenta.getValueAt(fila, 0).toString());
                List<dtofactura> listaF = verventaobject.EntregarComplementofactura();
                List<dtofactura> listaF2 = verventaobject.buscarfactura(idVenta, listaF);
                cargartablafactura2(listaF2);
            }
        }
    });

    // Clic en TablaFactura → rellena campos de Factura y Secretario
    TablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = TablaFactura.getSelectedRow();
            if (fila >= 0 && TablaFactura.getRowCount() > 0) {

                // --- Datos de la Factura ---
                InIDFactura.setText(TablaFactura.getValueAt(fila, 0).toString());
                InIDVenta.setText(TablaFactura.getValueAt(fila, 1).toString());
                InCantidadVenta.setText(TablaFactura.getValueAt(fila, 2).toString());
                InTotalVenta.setText(TablaFactura.getValueAt(fila, 3).toString());
                InFecha.setText(TablaFactura.getValueAt(fila, 4).toString());
                InIGVVenta.setText(TablaFactura.getValueAt(fila, 6).toString());
                InIDSecretario.setText(TablaFactura.getValueAt(fila, 8).toString());

                // --- Tabla Secretario → rellena Nombre, Apellido, Cédula ---
                String idSecretario = TablaFactura.getValueAt(fila, 8).toString();
                List<dtosecretario> listaS = verventaobject.EntregarComplementoSecretario();
                List<dtosecretario> listaS2 = verventaobject.buscarsecretario(idSecretario, listaS);
                cargarsecretario1(listaS2);
                for (dtosecretario dtos : listaS2) {
                    InIDSecretario.setText(dtos.getC().getIdSecretario());
                    InNombreSecretario.setText(dtos.getC().getNombre());
                    InApellidoSecretario.setText(dtos.getC().getApellido());
                    InCedulaSecretario.setText(dtos.getC().getCedula());
                }

                Mensaje.setText("Datos de factura y secretario cargados.");
            }
        }
    });

    Mensaje.setText("Tablas listas.");
}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InApellidoSecretario;
    private javax.swing.JTextField InCantidadVenta;
    private javax.swing.JTextField InCedulaSecretario;
    private javax.swing.JTextField InEstadoFactura;
    private javax.swing.JTextField InEstadoProducto;
    private javax.swing.JTextField InFecha;
    private javax.swing.JTextField InIDCliente;
    private javax.swing.JTextField InIDFactura;
    private javax.swing.JTextField InIDProducto;
    private javax.swing.JTextField InIDSecretario;
    private javax.swing.JTextField InIDVenta;
    private javax.swing.JTextField InIGVVenta;
    private javax.swing.JTextField InNombreCliente;
    private javax.swing.JTextField InNombreProducto;
    private javax.swing.JTextField InNombreSecretario;
    private javax.swing.JTextField InPrecioUnitarioProducto;
    private javax.swing.JTextField InSubTotalVenta;
    private javax.swing.JTextField InTotalVenta;
    private javax.swing.JTextArea Mensaje;
    private javax.swing.JPanel Producto;
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTable TablaFactura;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JTable TablaSecretario;
    private javax.swing.JTable TablaVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void verventas() {
        DefaultTableModel modelo = (DefaultTableModel) TablaVenta.getModel();
        String[] columnas = {"ID Venta", "IDCliente ", "IDProducto", "Valor a pagar", "FechaVenta", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);
        verventa vv = new verventa();
        List<dtoventa> lista = vv.Entrega();
        for (dtoventa dtov : lista) {
            modelo.addRow(new Object[]{
                dtov.getC().getIdVenta(),
                dtov.getC().getIdCliente(),
                dtov.getC().getIdProducto(),
                dtov.getC().getValorAPagar(),
                dtov.getC().getFechaVenta(),
                dtov.getC().getEstado()
            });
        }
        Mensaje.setText("Tabla de ventas actualizada.");

    }
    private dtoventa ventadto = new dtoventa();
private dtofactura facturadto = new dtofactura();

private int catidad;
    @Override
    public void crearventas() {
  
    
    }

    @Override
    public void actualizarventa() {
    
    }

    @Override
    public void eliminarventa() {

    
    }
private int idfacturageneral;
    public void cargartablafactura(List<dtofactura> lista2) {
        DefaultTableModel modelo = (DefaultTableModel) TablaFactura.getModel();
        String[] columnas = {"idFactura", "idVenta", "cantidad", "sub Total", "fecha", "coreo", "IVA", "IRPF", "idSecretario"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);

        verfactura vf = new verfactura();
        List<dtofactura> lista = lista2;

        for (dtofactura dtof : lista) {
            this.idfacturageneral=dtof.getC().getIdFactura();
            modelo.addRow(new Object[]{
                dtof.getC().getIdFactura(),
                dtof.getC().getIdVenta(),
                dtof.getC().getCantidad(),
                dtof.getC().getSubTotal(),
                dtof.getC().getFecha(),
                dtof.getC().getCorreo(),
                dtof.getC().getIva(),
                dtof.getC().getIrpf(),
                dtof.getC().getIdSecretario()
            });
        }
        Mensaje.setText("Tabla de facturas actualizada.");
   granactualizacion();
    }

    public void verproducto() {
   
  
    }

    public void versecretario() {
      

    }

    public void CargarTablaProducto(List<dtoproducto> lista2) {
        DefaultTableModel modelo = (DefaultTableModel) TablaProducto.getModel();
        String[] columnas = {"idProducto", "Nombre", "Cantidad", "Precio", "Descripcion", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);

        verfactura vf = new verfactura();
        List<dtoproducto> lista = lista2;

        for (dtoproducto dtop : lista) {
            this.preciofijo = dtop.getC().getPrecio();
            modelo.addRow(new Object[]{
                dtop.getC().getIdProducto(),
                dtop.getC().getNombre(),
                dtop.getC().getCantidad(),
                dtop.getC().getPrecio(),
                dtop.getC().getDescripcion(),
                dtop.getC().getEstado()
            }
            );
        }

        Mensaje.setText(
                "Tabla de productos actualizada.");
    }
private double preciofijo;
    public void verfactura() {
     
    }

    @Override
    public void cargarcliente1(List<dtocliente> lista) {
        DefaultTableModel modelo = (DefaultTableModel) TablaCliente.getModel();
        String[] columnas = {"ID+Cliente", "Nombre", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);
        for (dtocliente dtoc : lista) {

            modelo.addRow(new Object[]{
                dtoc.getC().getIdCliente(),
                dtoc.getC().getNombre(),
                dtoc.getC().getEstado()
            });

        }

    }

    @Override
    public void cargarsecretario1(List<dtosecretario> lista) {
        DefaultTableModel modelo = (DefaultTableModel) TablaSecretario.getModel();
        String[] columnas = {"ID+Secretario", "Nombre", "Apellido", "Cedula", "Telefono", "Direccion", "Estado"};
        modelo.setColumnIdentifiers(columnas);
        modelo.setRowCount(0);
        for (dtosecretario dtos : lista) {
            modelo.addRow(new Object[]{
                dtos.getC().getIdSecretario(),
                dtos.getC().getNombre(),
                dtos.getC().getApellido(),
                dtos.getC().getCedula(),
                dtos.getC().getTelefono(),
                dtos.getC().getDireccion(),
                dtos.getC().getEstado()
            });

        }
        String textomensaje = Mensaje.getText();
        Mensaje.setText(textomensaje + " secretario creado");
    }

    @Override
    public void cargarfactura1(List<dtofactura> lista) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void cargarventa1(List<dtoventa> lista) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void cargarproducto1(List<dtoproducto> lista) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void vercliente() {
          
    
    }

    public void actualizarcantidadproducto(int cantidadrestada, String ID){
    List<dtoproducto> lista1 = verventaobject.EntregarComplementoproducto();
    List<dtoproducto> lista2 = verventaobject.buscarproducto(ID, lista1);
    dtoproducto productoaactualizar = new dtoproducto();
    for(dtoproducto dtop : lista2){
        int CantidadBase = dtop.getC().getCantidad();
    dtop.getC().setCantidad(CantidadBase - cantidadrestada);
        productoaactualizar = dtop;
        
    }
        actualizarproducto actp = new actualizarproducto();
    actp.actualizardato(productoaactualizar);
        
    } 
    
    
    
    //65555555555555555555
    public void cargartablafactura2(List<dtofactura> lista2) {
    DefaultTableModel modelo = (DefaultTableModel) TablaFactura.getModel();
    String[] columnas = {"idFactura", "idVenta", "cantidad", "sub Total", "fecha", "coreo", "IVA", "IRPF", "idSecretario"};
    modelo.setColumnIdentifiers(columnas);
    modelo.setRowCount(0);

    for (dtofactura dtof : lista2) {
        this.idfacturageneral = dtof.getC().getIdFactura();
        modelo.addRow(new Object[]{
            dtof.getC().getIdFactura(),
            dtof.getC().getIdVenta(),
            dtof.getC().getCantidad(),
            dtof.getC().getSubTotal(),
            dtof.getC().getFecha(),
            dtof.getC().getCorreo(),
            dtof.getC().getIva(),
            dtof.getC().getIrpf(),
            dtof.getC().getIdSecretario()
        });

        // ← AQUÍ: cargar secretario y campos automáticamente
        String idSecretario = String.valueOf(dtof.getC().getIdSecretario());
        List<dtosecretario> listaS = verventaobject.EntregarComplementoSecretario();
        List<dtosecretario> listaS2 = verventaobject.buscarsecretario(idSecretario, listaS);
        cargarsecretario1(listaS2);
        for (dtosecretario dtos : listaS2) {
            InIDSecretario.setText(dtos.getC().getIdSecretario());
            InNombreSecretario.setText(dtos.getC().getNombre());
            InApellidoSecretario.setText(dtos.getC().getApellido());
            InCedulaSecretario.setText(dtos.getC().getCedula());
        }

        // Campos de la factura
        InIDFactura.setText(String.valueOf(dtof.getC().getIdFactura()));
        InCantidadVenta.setText(String.valueOf(dtof.getC().getCantidad()));
        InIGVVenta.setText(String.valueOf(dtof.getC().getIva()));
        InTotalVenta.setText(String.valueOf(dtof.getC().getSubTotal()));
    }

    Mensaje.setText("Tabla de facturas actualizada.");
    granactualizacion();
}
    private ClaseGenerarTxt cgt = new ClaseGenerarTxt();
    private void creararchivotxt(){
    String contenido = String.join(System.lineSeparator(),
            "========================================",
            "     AIRES ACONDICIONADOS AUTOMOTRIZ",
            "              ANTONI PERU",
            "           Lima, Peru - RUC: XXXXXXXXXX",
            "    Tel: XXX-XXXX | automotrizantoni@gmail.com",
            "========================================",
            "            FACTURA DE VENTA",
            "========================================",
            "Codigo Factura : " + InIDFactura.getText(),
            "Fecha          : " + InFecha.getText(),
            "Estado         : " + InEstadoFactura.getText(),
            "",
            "========================================",
            "           DATOS DEL CLIENTE",
            "========================================",
            "ID Cliente     : " + InIDCliente.getText(),
            "Nombre         : " + InNombreCliente.getText(),
            "",
            "========================================",
            "          DATOS DEL SECRETARIO",
            "========================================",
            "ID Secretario  : " + InIDSecretario.getText(),
            "Nombre         : " + InNombreSecretario.getText(),
            "Apellido       : " + InApellidoSecretario.getText(),
            "Cedula         : " + InCedulaSecretario.getText(),
            "",
            "========================================",
            "          DETALLE DE LA VENTA",
            "========================================",
            "Codigo Venta   : " + InIDVenta.getText(),
            "Cantidad       : " + InCantidadVenta.getText(),
            "Subtotal       : S/ " + InSubTotalVenta.getText(),
            "IGV (18%)      : S/ " + InIGVVenta.getText(),
            "TOTAL          : S/ " + InTotalVenta.getText(),
            "",
            "========================================",
            "              PRODUCTO",
            "========================================",
            "Codigo Producto: " + InIDProducto.getText(),
            "Nombre         : " + InNombreProducto.getText(),
            "Precio Unitario: S/ " + InPrecioUnitarioProducto.getText(),
            "Estado         : " + InEstadoProducto.getText(),
            "",
            "========================================",
            "  Gracias por su compra en AUTOMOTRIZ",
            "            ANTONI PERU",
            "  'Calidad y confianza en cada servicio'",
            "  Lima, Peru | automotrizantoni@gmail.com",
            "  Atendido por: " + InNombreSecretario.getText()
                + " " + InApellidoSecretario.getText(),
            "========================================"
        );
    cgt.generarTxt(InIDFactura.getText(), contenido);
    String TextoMensaje = Mensaje.getText();
    Mensaje.setText(TextoMensaje+"\n Se creo la factura .txt");
    }
    public void limpiarCampos() {
    // Factura
    InIDFactura.setText("");
    InFecha.setText("");
    InEstadoFactura.setText("");

    // Cliente
    InIDCliente.setText("");
    InNombreCliente.setText("");

    // Secretario
    InIDSecretario.setText("");
    InNombreSecretario.setText("");
    InApellidoSecretario.setText("");
    InCedulaSecretario.setText("");

    // Venta
    InIDVenta.setText("");
    InCantidadVenta.setText("");
    InSubTotalVenta.setText("");
    InIGVVenta.setText("");
    InTotalVenta.setText("");

    // Producto
    InIDProducto.setText("");
    InNombreProducto.setText("");
    InPrecioUnitarioProducto.setText("");
    InEstadoProducto.setText("");

    Mensaje.setText("Campos limpiados.");
}
}
