/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.elaboraciondeactividadesdelaorganizacion.VistaControl.administrador;

import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.controller.interfaseguisecretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.dto.dtosecretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.model.secretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.BaseDeTransformacion;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.Resoluciondecambios.DeStringaInt;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.actualizarsecretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.crearsecretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.eliminarsecretario;
import com.mycompany.elaboraciondeactividadesdelaorganizacion.Modelo.service.versecretario;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author x
 */
public class AdministrandoSecretarioEmpleadoGUI extends javax.swing.JFrame implements interfaseguisecretario{

    /**
     * Creates new form MenuAdministradorGUI
     */
    public AdministrandoSecretarioEmpleadoGUI() {
        initComponents();
        movimientomouse();
        versecretarios();
    }

    
    private void movimientomouse(){
      Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = Tabla.getSelectedRow();
            if (fila >= 0) {
                InIDSecretario.setText(Tabla.getValueAt(fila, 0).toString());
                InNombre.setText(Tabla.getValueAt(fila, 1).toString());
                InApelldio.setText(Tabla.getValueAt(fila, 2).toString());
                InCedula.setText(Tabla.getValueAt(fila, 3).toString());
                InTelefono.setText(Tabla.getValueAt(fila, 4).toString());
                InDireccion.setText(Tabla.getValueAt(fila, 5).toString());
                InEstado.setText(Tabla.getValueAt(fila, 6).toString());
            }
        }
    });
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InIDSecretario = new javax.swing.JTextField();
        InNombre = new javax.swing.JTextField();
        InApelldio = new javax.swing.JTextField();
        InCedula = new javax.swing.JTextField();
        InTelefono = new javax.swing.JTextField();
        InEstado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        Mensaje = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        InDireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Administracion de los secretarios");

        jLabel2.setText("IDSecretario");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Cedula");

        jLabel6.setText("Telefono");

        jLabel7.setText("Estado");

        InNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNombreActionPerformed(evt);
            }
        });

        InApelldio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InApelldioActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jLabel8.setText("Mensaje....>");

        Mensaje.setText("...");
        Mensaje.setOpaque(true);

        jLabel9.setText("DIreccion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InIDSecretario, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(InNombre)
                                    .addComponent(InApelldio)
                                    .addComponent(InCedula)
                                    .addComponent(InTelefono)
                                    .addComponent(InEstado)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(InDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InIDSecretario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(InNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(InApelldio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(InCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(InTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(InDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InNombreActionPerformed

    private void InApelldioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InApelldioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InApelldioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
MenuAdministrador ma = new MenuAdministrador();
ma.setVisible(true);
        AdministrandoSecretarioEmpleadoGUI.this.dispose();
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualizarsecretario();
        versecretarios();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   eliminarsecretario();
   versecretarios();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       InIDSecretario.setText("");
    InNombre.setText("");
    InApelldio.setText("");
    InCedula.setText("");
    InTelefono.setText("");
    InDireccion.setText("");
    InEstado.setText("");
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearsecretario();
        versecretarios();
    }//GEN-LAST:event_jButton1ActionPerformed

   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InApelldio;
    private javax.swing.JTextField InCedula;
    private javax.swing.JTextField InDireccion;
    private javax.swing.JTextField InEstado;
    private javax.swing.JTextField InIDSecretario;
    private javax.swing.JTextField InNombre;
    private javax.swing.JTextField InTelefono;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void versecretarios() {
 
    String[] columnas = {"ID Secretario", "Nombre", "Apellido", "Cedula", "Telefono", "Direccion", "Estado"};
    DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
    modelo.setColumnIdentifiers(columnas);
    modelo.setRowCount(0);

    versecretario vs = new versecretario();
    List<dtosecretario> lista = vs.Entrega();

    Object[] objeto = new Object[7];
    for (dtosecretario dtos : lista) {
        objeto[0] = dtos.getC().getIdSecretario();
        objeto[1] = dtos.getC().getNombre();
        objeto[2] = dtos.getC().getApellido();
        objeto[3] = dtos.getC().getCedula();
        objeto[4] = dtos.getC().getTelefono();
        objeto[5] = dtos.getC().getDireccion();
        objeto[6] = dtos.getC().getEstado();
        modelo.addRow(objeto);
    }

    this.Mensaje.setText("Se actualizo los datos de la tabla");
}
    
    
    

    @Override
    public void crearsecretario() {
  crearsecretario cs = new crearsecretario();
    BaseDeTransformacion<String, Integer> A = new DeStringaInt();

    secretario s = new secretario();
    s.setIdSecretario(InIDSecretario.getText());
    s.setNombre(InNombre.getText());
    s.setApellido(InApelldio.getText());
    s.setCedula(InCedula.getText());
    s.setTelefono(InTelefono.getText());
    s.setDireccion(InDireccion.getText());
    s.setEstado(A.Tranformacion(InEstado.getText()));

    dtosecretario dtos = new dtosecretario(s);
    Mensaje.setText(cs.regusitrar(dtos));

    
    }

    @Override
    public void actualizarsecretario() {
  actualizarsecretario as = new actualizarsecretario();
    BaseDeTransformacion<String, Integer> A = new DeStringaInt();

    secretario s = new secretario();
    s.setIdSecretario(InIDSecretario.getText());
    s.setNombre(InNombre.getText());
    s.setApellido(InApelldio.getText());
    s.setCedula(InCedula.getText());
    s.setTelefono(InTelefono.getText());
    s.setDireccion(InDireccion.getText());
    s.setEstado(A.Tranformacion(InEstado.getText()));

    dtosecretario dtos = new dtosecretario(s);
    Mensaje.setText(as.actualizardato(dtos));
    }

    @Override
    public void eliminarsecretario() {
     eliminarsecretario es = new eliminarsecretario();
    BaseDeTransformacion<String, Integer> A = new DeStringaInt();

    secretario s = new secretario();
    s.setIdSecretario(InIDSecretario.getText());
    s.setNombre(InNombre.getText());
    s.setApellido(InApelldio.getText());
    s.setCedula(InCedula.getText());
    s.setTelefono(InTelefono.getText());
    s.setDireccion(InDireccion.getText());
    s.setEstado(A.Tranformacion(InEstado.getText()));

    dtosecretario dtos = new dtosecretario(s);
    Mensaje.setText(es.eliminardato(dtos));
    }
}
